# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'petitui' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_modular_headers! 
  use_frameworks!
  pod 'SkyFloatingLabelTextField'
  pod 'Alamofire'
  pod 'MessageKit'
  pod 'MBRadioCheckboxButton'
  pod 'RevealingSplashView'
  pod 'FaveButton'
  # Pods for petitui

end
